import {muscleSeed} from './muscle-data.js';
import {validateMuscleTables} from './muscle-actions.js';
import {DATABASE_VERSION,stores,BASE_STORES,repository,normalizeSessionSlots,normalizeTrialMovements} from './store.js';
import {initialConfiguration,initialExercises,initialGoals,validateGoalGraph} from './config.js';
import {phase2Seed} from './training-data.js';
import {validatePersonalBlock} from './schedule.js';
import {gameSeeds,legacyLedger} from './game-data.js';
import {validateGameTables} from './game-backup.js';
const array=(v,label)=>{if(!Array.isArray(v))throw Error('Invalid '+label);return v};
const num=(v,min,max,label)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error('Invalid '+label)};
const text=(v,label)=>{if(typeof v!=='string'||v.length>10000)throw Error('Invalid '+label)};
const date=v=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw Error('Invalid record date')};
// Backup-format migrations are independent of IndexedDB upgrade migrations.
export const backupMigrations={1:backup=>{for(const s of BASE_STORES)array(backup.tables[s],s);return {...backup,format:'kitty-quest-backup',schemaVersion:2,tables:{...backup.tables,configurations:[initialConfiguration],exercises:initialExercises,goals:initialGoals,dailyStates:[],edits:[]}}},2:backup=>({...backup,schemaVersion:3,tables:{...backup.tables,sessions:normalizeSessionSlots(array(backup.tables.sessions,'sessions'))}})};
backupMigrations[3]=backup=>{const seed=phase2Seed(),prior=array(backup.tables.exercises,'exercises');return {...backup,schemaVersion:4,tables:{...backup.tables,exercises:[...seed.exercises.map(e=>({...e,...(prior.find(p=>p.id===e.id)?{name:prior.find(p=>p.id===e.id).name}: {})})),...prior.filter(p=>!seed.exercises.some(e=>e.id===p.id))],skillDefinitions:seed.skills,soreness:[],equipmentProfiles:seed.equipment,records:[],recordEvents:[],masteryAwards:[],personalRecurrences:[]}}};
backupMigrations[4]=backup=>({...backup,schemaVersion:5,tables:{...backup.tables,skillDefinitions:normalizeTrialMovements(backup.tables.skillDefinitions)}});
backupMigrations[5]=backup=>{const seed=gameSeeds();return {...backup,schemaVersion:6,tables:{...backup.tables,gameConfigurations:[seed.configuration],rewardLedger:legacyLedger(backup.tables.rewards),gameQuests:[],gameBadges:[],bossClears:[],pillarPlans:[],gameInventory:[seed.inventory,seed.title],gameProfile:[seed.profile],gameCelebrations:[]}}};
backupMigrations[6]=backup=>{const seed=muscleSeed(backup.tables.exercises,backup.tables.skillDefinitions);return {...backup,schemaVersion:7,tables:{...backup.tables,exercises:[...backup.tables.exercises,...seed.exercises.filter(e=>!backup.tables.exercises.some(x=>x.id===e.id))],skillDefinitions:[...backup.tables.skillDefinitions.filter(s=>!seed.skills.some(n=>n.id===s.id)),...seed.skills],musclePaths:seed.paths,progressionPolicies:[]}}};
backupMigrations[7]=backup=>{const seed=muscleSeed(backup.tables.exercises,backup.tables.skillDefinitions),definitions=[...backup.tables.skillDefinitions.filter(s=>!seed.skills.some(n=>n.id===s.id)),...seed.skills];return {...backup,schemaVersion:8,tables:{...backup.tables,skillDefinitions:definitions,exercises:backup.tables.exercises.map(e=>({...e,relatedDominancePath:e.relatedDominancePath||definitions.find(s=>s.id==='exercise:'+e.id)?.id||definitions.find(s=>s.levelDefinitions.some(l=>l.exerciseId===e.id))?.id||null})),musclePaths:seed.paths.map(p=>backup.tables.musclePaths.find(x=>x.id===p.id&&x.revision!==1)||p)}}};
export function validateBackup(input){let backup=structuredClone(input);if(!backup||!Number.isInteger(backup.schemaVersion)||backup.schemaVersion<1||backup.schemaVersion>DATABASE_VERSION)throw Error('Unsupported backup version.');if(!backup.tables||typeof backup.tables!=='object')throw Error('Backup tables are missing.');while(backup.schemaVersion<DATABASE_VERSION)backup=backupMigrations[backup.schemaVersion](backup);if(backup.format!=='kitty-quest-backup')throw Error('Not a Kitty Quest backup.');if(Object.keys(backup.tables).some(k=>!stores.includes(k)))throw Error('Unexpected backup table.');for(const store of stores){const rows=array(backup.tables[store],store),ids=new Set();if(rows.length>100000)throw Error('Backup table is too large.');for(const r of rows){if(!r||typeof r!=='object'||typeof r.id!=='string'||!r.id||ids.has(r.id))throw Error('Invalid or duplicate ID in '+store);ids.add(r.id);if(r.date!==undefined)date(r.date)}}
 const t=backup.tables;
 for(const r of t.preferences){text(r.name,'player name');num(r.waterTarget,1,256,'water target');date(r.transformationStart);if(!r.memory||Object.values(r.memory).some(v=>typeof v!=='boolean'))throw Error('Invalid memory preferences');if(!['Quiet','Command','Coach','Planner','Builder'].includes(r.mode))throw Error('Invalid Caelum mode')}
 for(const r of t.sessions){if(!['Main','Second','Extra','Sports','Custom'].includes(r.kind)||!['planned','active','paused','completed','partial'].includes(r.status))throw Error('Invalid session lifecycle');date(r.date);text(r.name,'session name');for(const e of array(r.exercises,'session exercises')){text(e.name,'exercise name');num(e.sets,1,100,'sets');num(e.reps,1,1000,'target reps');num(e.weight,0,2000,'resistance')}const ids=new Set();for(const l of array(r.logs,'session logs')){if(typeof l.id!=='string'||ids.has(l.id)||!r.exercises[l.exercise])throw Error('Invalid set reference');ids.add(l.id);text(l.name,'set name');num(l.reps,0,1000,'reps');num(l.weight,0,2000,'weight');num(l.difficulty,1,10,'difficulty');for(const k of ['durationSeconds','distanceMeters','restSeconds'])if(l[k]!==undefined)num(l[k],0,100000,k);for(const k of ['form','pain','tempoControlled'])if(l[k]!==undefined&&typeof l[k]!=='boolean')throw Error('Invalid '+k);if(l.notes!==undefined)text(l.notes,'set notes')}}
 const slots=new Set();for(const s of t.sessions.filter(s=>['Main','Second'].includes(s.kind))){const key=s.date+':'+s.kind;if(s.supersededBy){if(!t.sessions.some(p=>p.id===s.supersededBy&&p.date===s.date&&p.kind===s.kind&&!p.supersededBy))throw Error('Invalid archived slot reference');if(s.slotKey)throw Error('Archived duplicate cannot own a daily slot');continue}if(s.slotKey!==key||slots.has(key))throw Error('Invalid or duplicate daily workout slot');slots.add(key)}
 for(const w of t.water){date(w.date);num(w.amount,0.1,256,'water amount')}
 for(const r of t.routineLogs){date(r.date);num(r.task,0,100,'routine task');if(typeof r.done!=='boolean')throw Error('Invalid routine completion')}
 for(const e of t.events){date(e.date);text(e.name,'event name');if(e.category==='Personal Time'){validatePersonalBlock(e);if(e.protected!==true)throw Error('Personal Time must stay protected.')}else if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.time)||!['PLANNED','COMPLETED','SKIPPED','MOVED','MISSED'].includes(e.status))throw Error('Invalid schedule event')}
 for(const a of t.attempts){text(a.skill,'skill');text(a.trial,'trial');date(a.date);for(const [key,max] of [['level',100],['sets',100],['reps',1000],['seconds',100000],['distance',100000]])num(a[key],0,max,key);if(a.load!==undefined)num(a.load,0,2000,'load');num(a.difficulty,1,10,'difficulty');if(typeof a.form!=='boolean'||typeof a.pain!=='boolean')throw Error('Invalid mastery evidence')}
 for(const m of t.metrics){date(m.date);if(m.weight!==null)num(m.weight,50,1000,'body weight');if(m.waist!==null)num(m.waist,10,100,'waist');text(m.notes||'','metric notes')}
 for(const c of t.checkins){date(c.date);num(c.sleep,0,24,'sleep');num(c.energy,1,10,'energy');num(c.hunger,1,10,'hunger');num(c.soreness,0,10,'soreness');text(c.performance||'','performance note');if(c.photo){if(!['Front relaxed','Side relaxed','Back relaxed','Front flex','Side flex','Back flex'].includes(c.pose)||typeof c.photo!=='string'||c.photo.length>8_000_000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(c.photo))throw Error('Invalid original progress photo');if(c.type!=='progress-photo')throw Error('Progress photo needs a photo check-in')}}
 for(const r of t.rewards){date(r.date);num(r.xp,0,100000,'XP');num(r.coins,0,100000,'coins');if(r.id.startsWith('session:')&&!t.sessions.some(s=>'session:'+s.id===r.id&&s.status==='completed'))throw Error('Reward has no completed source session')}
 for(const c of t.configurations){num(c.startWeight,50,1000,'starting weight');num(c.goalLow,50,1000,'goal low');num(c.goalHigh,c.goalLow,1000,'goal high');num(c.laterMilestone,50,1000,'later milestone');num(c.durationWeeks,1,104,'duration');num(c.weeklyLossLow,0,5,'weekly loss low');num(c.weeklyLossHigh,c.weeklyLossLow,5,'weekly loss high')}
 if(!t.configurations.some(c=>c.id==='transformation'))throw Error('Transformation configuration is missing.');
 for(const e of t.exercises){text(e.name,'exercise');text(e.movementType,'movement type');for(const k of ['targetMuscles','equipment','regressions','alternatives','progressions'])for(const v of array(e[k],k))text(v,k);if(!e.safety||!e.dominanceRules)throw Error('Exercise safety and dominance metadata are required');for(const cue of array(e.safety.cues,'safety cues'))text(cue,'safety cue');text(e.dominanceRules.protocol,'dominance protocol')}
 for(const g of t.goals){text(g.name,'goal name');array(g.dependsOn,'goal dependencies')}validateGoalGraph(t.goals);
 for(const e of t.edits){if(!t.sessions.some(s=>s.id===e.recordId&&s.logs.some(l=>l.id===e.setId)))throw Error('Correction has no source set');text(e.reason,'correction reason');if(!e.before||!e.after)throw Error('Correction snapshots are missing')}
 for(const d of t.dailyStates){date(d.date);if(d.id!==d.date)throw Error('Invalid daily state key')}
 for(const template of t.templates){if(template.tasks)for(const task of array(template.tasks,'routine tasks'))text(task,'task');if(template.type==='workout'){text(template.name,'template name');for(const e of array(template.exercises,'template exercises')){text(e.name,'exercise');num(e.sets,1,100,'sets');num(e.reps,1,1000,'reps');num(e.weight,0,2000,'resistance')}}if(template.type==='schedule'){text(template.name,'day type');for(const e of array(template.events,'template events')){text(e.name,'event name');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.time))throw Error('Invalid template time');num(e.buffer,0,240,'buffer')}}}
 for(const s of t.soreness){date(s.date);text(s.muscle,'muscle');num(s.rating,0,4,'soreness');if(!Number.isInteger(s.rating))throw Error('Invalid soreness rating');text(s.at,'soreness time')}
 for(const p of t.equipmentProfiles){text(p.name,'equipment profile');for(const e of array(p.equipment,'equipment'))text(e,'equipment')}
 for(const skill of t.skillDefinitions){text(skill.name,'skill name');const levels=array(skill.levelDefinitions,'skill levels'),ids=new Set();if(!levels.length)throw Error('Skill needs levels');for(const l of levels){text(l.id,'level id');if(ids.has(l.id))throw Error('Duplicate level id');ids.add(l.id);text(l.name,'level name');if(!t.exercises.some(e=>e.id===l.exerciseId))throw Error('Skill exercise is missing');num(l.sessions,1,100,'qualifying days');const trials=new Set();for(const r of array(l.requirements,'trial rules')){text(r.id,'trial id');if(trials.has(r.id))throw Error('Duplicate trial id');trials.add(r.id);text(r.label,'trial label');text(r.pillar,'pillar');num(r.sets,1,100,'trial sets');for(const k of ['reps','load','seconds','distance'])if(r[k]!==undefined)num(r[k],0,100000,'trial '+k)}}}
 for(const a of t.masteryAwards){if(a.id!==a.skill+':'+a.levelId||!t.skillDefinitions.some(s=>s.id===a.skill&&s.levelDefinitions.some(l=>l.id===a.levelId)))throw Error('Invalid mastery award');date(a.date);text(a.name,'mastery name')}
 for(const r of [...t.records,...t.recordEvents]){num(r.value,0,10000000,'record value');if(!t.sessions.some(s=>s.id===r.sourceSession&&s.logs.some(l=>l.id===r.sourceSet)))throw Error('PR source set is missing');text(r.type,'record type');text(r.unit,'record unit')}
 for(const r of t.personalRecurrences)validatePersonalBlock(r,true);
 validateGameTables(t);validateMuscleTables(t);
 return backup;
}
export function backupSummary(backup){return {version:backup.schemaVersion,records:Object.values(backup.tables).reduce((s,rows)=>s+rows.length,0),sessions:backup.tables.sessions.length,exportedAt:backup.exportedAt}}
export async function restoreBackup(input,repo=repository){const backup=validateBackup(input);if(backup.profile==='test'&&repo.name!=='kitty-quest-test-profile')throw Error('This is a Test Mode backup. Enter Test Mode to restore it without mixing test activity into real progress.');return repo.transact(stores,async t=>{const previous={format:'kitty-quest-backup',profile:repo.name==='kitty-quest-test-profile'?'test':'real',schemaVersion:DATABASE_VERSION,exportedAt:new Date().toISOString(),tables:Object.fromEntries(await Promise.all(stores.map(async s=>[s,await t.all(s)])))};for(const s of stores){await t.clear(s);for(const record of backup.tables[s])await t.put(s,record)}return {previous,summary:backupSummary(backup)}})}
// Future old-app adapters must return a validated backup; no legacy importer yet.
export function legacyImportAdapter(){throw Error('Legacy migration is deferred. Only versioned Kitty Quest backups are supported.')}
