import {gameStores,cosmetics,bosses,pillars} from './game-data.js';
export function validateGameTables(t){const error=message=>{throw Error('Invalid game backup: '+message)};const integer=(v,min,max)=>Number.isInteger(v)&&v>=min&&v<=max;const text=v=>typeof v==='string'&&v.length<=10000;const c=t.gameConfigurations.find(c=>c.id==='economy');if(!c||!integer(c.levelBase,100,100000)||!integer(c.levelStep,0,100000))error('XP curve');for(const k of ['pillarXP','quadXP','routineDailyXP','prDailyXP','trialDailyXP','checkinDailyXP','questXP','questCoins'])if(!integer(c[k],0,1000))error('economy '+k);for(const k of ['sessionDailyLimit','questDailyLimit'])if(!integer(c[k],1,10))error('daily caps');if(!c.transformation||!integer(c.transformation.trendDays,3,30)||!integer(c.transformation.minimumSamples,3,30)||!integer(c.transformation.minimumCheckins,1,100)||!Number.isFinite(c.transformation.weightChange)||c.transformation.weightChange<=0||!Number.isFinite(c.transformation.waistChange)||c.transformation.waistChange<=0||!c.weekly||!integer(c.weekly.mobilitySessions,1,7)||!integer(c.weekly.quadDays,1,7))error('milestone configuration');
 const types=['legacy','session','pillar','quad','routine','checkin','pr','trial','quest','badge','boss','level','purchase','safetyStop'];let xp=0,coins=0;for(const r of t.rewardLedger){if(!types.includes(r.sourceType)||r.id!==r.sourceType+':'+r.sourceId||!integer(r.amount,0,100000)||!integer(r.coins,r.sourceType==='purchase'?-100000:0,100000)||!text(r.reason)||!text(r.at)||!r.date||!r.evidence)error('ledger transaction');if(r.sourceType==='purchase'&&(r.amount!==0||!cosmetics.some(c=>c.id===r.sourceId&&r.coins===-c.cost)))error('cosmetic debit');if(r.sourceType==='session'&&!t.sessions.some(s=>s.id===r.sourceId&&s.status==='completed'))error('session reward source');if(r.sourceType==='legacy'&&!t.rewards.some(s=>s.id===r.sourceId&&s.xp===r.amount&&s.coins===r.coins))error('legacy reward source');if(r.sourceType==='boss'&&!t.bossClears.some(b=>b.id===r.sourceId))error('boss reward source');if(r.sourceType==='badge'&&!t.gameBadges.some(b=>b.id===r.sourceId))error('badge reward source');if(r.sourceType==='quest'&&!t.gameQuests.some(q=>q.id===r.sourceId&&q.status==='completed'))error('quest reward source');xp+=r.amount;coins+=r.coins}if(xp<0||coins<0)error('negative balance');
 for(const p of t.pillarPlans){if(p.id!==p.date||!Array.isArray(p.items)||p.items.length!==4||new Set(p.items.map(i=>i.id)).size!==4||p.items.some(i=>!pillars.some(p=>p.id===i.id)||typeof i.planned!=='boolean'||!['Normal','Light / Rebuild','Recovery'].includes(i.mode))||!p.completed||typeof p.requireWater!=='boolean')error('pillar plan');for(const [id,v] of Object.entries(p.completed))if(!pillars.some(p=>p.id===id)||!t.sessions.some(s=>s.id===v.sessionId&&s.status==='completed')||!text(v.at))error('pillar evidence')}
 for(const q of t.gameQuests){if(!text(q.name)||!['planned','completed','archived'].includes(q.status)||!['Daily','Weekly','Dominance','Side','Recovery','Personal','Boss','Transformation'].includes(q.type)||!integer(q.minutes,1,1440)||!integer(q.priority,1,10)||!q.reward||!integer(q.reward.xp,0,1000)||!integer(q.reward.coins,0,1000)||!Array.isArray(q.evidence)||q.status==='completed'&&!q.completedAt)error('quest');if(q.condition==='trial'&&!t.skillDefinitions.some(s=>s.id===q.skill&&s.levelDefinitions.some(l=>l.id===q.levelId)))error('quest skill')}
 for(const b of t.gameBadges){if(!text(b.name)||!text(b.description)||!['Common','Uncommon','Rare','Epic','Legendary'].includes(b.rarity)||!Array.isArray(b.evidence)||!b.evidence.length||!b.reward||!integer(b.reward.xp,0,100000)||!integer(b.reward.coins,0,100000)||!b.date)error('badge')}
 for(const b of t.bossClears){if(!bosses.some(d=>d.id===b.id)||!text(b.name)||!Array.isArray(b.evidence)||!b.evidence.length||!b.stats||!b.reward||!b.date)error('boss clear')}
 for(const item of t.gameInventory){if(!['title','cosmetic'].includes(item.type)||item.id!==item.type+':'+item.itemId||!text(item.name)||item.type==='cosmetic'&&!cosmetics.some(c=>c.id===item.itemId))error('inventory')}
 const p=t.gameProfile.find(p=>p.id==='player');if(!p||!t.gameInventory.some(i=>i.type==='title'&&i.itemId===p.title)||!Array.isArray(p.favorites)||p.favorites.length>3||p.favorites.some(id=>!t.gameBadges.some(b=>b.id===id))||!p.equipped||Object.entries(p.equipped).some(([slot,id])=>!cosmetics.some(c=>c.id===id&&c.slot===slot)||!t.gameInventory.some(i=>i.id==='cosmetic:'+id)))error('equipped profile');
 for(const item of t.gameCelebrations)if(!['badge','boss','level'].includes(item.type)||typeof item.seen!=='boolean'||!text(item.name)||!Array.isArray(item.evidence))error('celebration');
}
