// Configuration only. All evidence lives in the shared Dominance tables.
export const muscleRegions={Arms:['Biceps','Triceps','Forearms'],Shoulders:['Shoulders','Front Delts','Side Delts','Rear Delts'],Chest:['Chest','Upper Chest','Mid Chest','Lower Chest'],Back:['Back','Lats','Upper Back','Mid Back','Traps','Lower Back'],Core:['Abs','Obliques','Deep Core','Lower Core','Spinal Stability'],Lower:['Quads','Hamstrings','Glutes','Calves','Hips']};
export const muscleNames=[...new Set(Object.values(muscleRegions).flat())];
export function exerciseTargets(e,name){const n=name.toLowerCase();return e.targetMuscles.some(m=>m.toLowerCase()===n)||(n==='back'&&e.category==='Back')||(n==='chest'&&e.category==='Chest')||(n==='spinal stability'&&e.targetMuscles.includes('stability'))||(n==='mid chest'&&['chest-press','dumbbell-press','pushup'].includes(e.id))||(n==='front delts'&&['shoulder-press','chest-press','dumbbell-press'].includes(e.id))||(n==='mid back'&&e.id==='row')}
const rows=[
 ['hammer-curl','Hammer curl','Biceps','elbow flexion','biceps,forearms','dumbbells'],['cable-curl','Cable curl','Biceps','elbow flexion','biceps','cables'],['preacher-curl','Preacher curl','Biceps','elbow flexion','biceps','dumbbells'],['machine-curl','Machine curl','Biceps','elbow flexion','biceps','machines'],['chinup','Chin-up','Back','vertical pull','lats,biceps,forearms','pull-up bar'],
 ['db-triceps','Dumbbell triceps extension','Triceps','elbow extension','triceps','dumbbells'],['pushdown','Cable triceps pushdown','Triceps','elbow extension','triceps','cables'],['overhead-triceps','Overhead triceps extension','Triceps','elbow extension','triceps','dumbbells'],['skullcrusher','Dumbbell skullcrusher','Triceps','elbow extension','triceps','dumbbells'],['assisted-dip','Assisted dip','Triceps','vertical push','triceps,lower chest,shoulders','machines'],['dip','Dip','Triceps','vertical push','triceps,lower chest,shoulders','dip bars'],['closegrip-pushup','Close-grip push-up','Triceps','horizontal push','triceps,chest,front delts',''],
 ['wrist-curl','Wrist curl','Forearms','wrist flexion','forearms','dumbbells'],['reverse-wrist','Reverse wrist curl','Forearms','wrist extension','forearms','dumbbells'],['reverse-curl','Reverse curl','Forearms','elbow flexion','forearms,biceps','dumbbells'],
 ['lateral-raise','Lateral raise','Shoulders','shoulder abduction','side delts,shoulders','dumbbells'],['front-raise','Front raise','Shoulders','shoulder flexion','front delts,shoulders','dumbbells'],['rear-fly','Rear delt fly','Shoulders','horizontal abduction','rear delts,upper back,shoulders','dumbbells'],['facepull','Cable face pull','Shoulders','horizontal pull','rear delts,upper back,shoulders','cables'],
 ['incline-press','Incline dumbbell press','Chest','horizontal push','upper chest,chest,triceps,front delts','dumbbells'],['chest-fly','Cable chest fly','Chest','horizontal adduction','mid chest,chest','cables'],['cable-row','Cable row','Back','horizontal pull','mid back,back,lats,biceps','cables'],['shrug','Dumbbell shrug','Back','scapular elevation','traps,upper back','dumbbells'],['back-extension','Back extension','Back','spinal extension','lower back,spinal stability,glutes',''],
 ['leg-raise','Supported leg raise','Core','trunk flexion','abs,lower core',''],['cable-crunch','Cable crunch','Core','trunk flexion','abs','cables'],['hollow','Hollow hold','Core','core stability','abs,deep core,lower core',''],['pallof','Pallof press','Core','anti rotation','obliques,deep core,spinal stability','bands'],
 ['leg-extension','Leg extension','Quads','knee extension','quads','machines'],['split-squat','Split squat','Quads','squat','quads,glutes,hips',''],['leg-curl','Leg curl','Hamstrings','knee flexion','hamstrings','machines'],['rdl','Dumbbell Romanian deadlift','Hamstrings','hinge','hamstrings,glutes,lower back','dumbbells'],['hip-thrust','Hip thrust','Glutes','hip extension','glutes,hamstrings','dumbbells'],['seated-calf','Seated calf raise','Calves','ankle extension','calves','machines'],['hip-abduction','Hip abduction','Hips','hip abduction','hips,glutes','machines'],['hip-adduction','Hip adduction','Hips','hip adduction','hips','machines'],['hip-control','Standing hip control','Hips','hip control','hips,deep core','']
];
export const muscleExercises=rows.map(([id,name,category,movementType,muscles,equipment])=>({id,name,category,movementType,targetMuscles:muscles.split(','),primaryMuscles:muscles.split(',').slice(0,1),secondaryMuscles:muscles.split(',').slice(1),equipment:equipment?[equipment]:[],difficulty:['dip','chinup'].includes(id)?4:1,skillType:'strength',laterality:'bilateral',resistance:id==='assisted-dip'?'assistance':equipment&&!['pull-up bar','dip bars'].includes(equipment)?'weighted':'bodyweight',measurement:['hollow','hip-control'].includes(id)?'duration':'reps',regressions:id==='dip'?['assisted-dip']:id==='chinup'?['assisted-pullup']:[],alternatives:[],progressions:id==='assisted-dip'?['dip']:[],supportedPRTypes:['weight','reps','controlled-reps'],relatedDominancePath:'exercise:'+id,dominanceRules:{protocol:'Controlled strength, endurance, and repeatability on separate practice days',requiresRepeatability:true},safety:{painStopsProof:true,explosive:false,highVolumeEligible:false,cues:['Choose a comfortable range and appropriate resistance','Control the movement; stop when painful']},builtIn:true}));
export const ladderFor=e=>e.resistance==='assistance'||e.id==='assisted-pullup'?{direction:'decreasing',unit:'lb assistance',values:[100,80,60,40,20]}:e.resistance==='bodyweight'?{direction:'variation',unit:e.measurement==='duration'?'seconds':'reps',values:e.measurement==='duration'?[15,25,40]:[5,8,12]}:{direction:'increasing',unit:'lb',values:e.equipment?.some(v=>['machines','cables'].includes(v))?[50,55,60,65]:[5,8,10,12,15,20]};
export function exerciseSkill(e,ladder=ladderFor(e)){return {id:'exercise:'+e.id,name:e.name+' / capability',exerciseId:e.id,musclePath:true,ladder,levelDefinitions:ladder.values.map(value=>{const measure=ladder.direction==='variation'?e.measurement==='duration'?{seconds:value}:{reps:value}:{reps:8};const rule=(id,pillar,extra={})=>({id,pillar,label:pillar+' · '+value+' '+ladder.unit,exerciseId:e.id,sets:2,...measure,...(ladder.direction!=='variation'?{load:value,loadComparison:ladder.direction==='decreasing'?'atMost':'atLeast'}:{}),requiresForm:true,maxDifficulty:8,...extra});return {id:'exercise:'+e.id+':tier:'+value,name:value+' '+ladder.unit,exerciseId:e.id,sessions:3,requirements:[rule('strength','Strength'),rule('control','Control',{tempo:true}),rule('endurance','Endurance',e.measurement==='duration'?{seconds:Math.round(value*1.5)}:{reps:ladder.direction==='variation'?Math.max(value,12):12})]}})}}
export function muscleSeed(existingExercises,existingSkills){const exercises=[...existingExercises,...muscleExercises.filter(e=>!existingExercises.some(x=>x.id===e.id))];const skills=exercises.filter(e=>!['Running','Mobility','Carry','Hands'].includes(e.category)&&!existingSkills.some(s=>s.levelDefinitions.some(l=>l.exerciseId===e.id))).map(e=>exerciseSkill(e));const curl=existingSkills.find(s=>s.id==='curl');if(curl&&!curl.ladder&&curl.levelDefinitions.map(l=>Math.max(...l.requirements.map(r=>r.load||0))).every((v,i,values)=>!i||v>values[i-1]))skills.push({...curl,ladder:{direction:'increasing',unit:'lb',values:curl.levelDefinitions.map(l=>Math.max(...l.requirements.map(r=>r.load||0)))}});const all=[...existingSkills.filter(s=>!skills.some(n=>n.id===s.id)),...skills];const primary={Biceps:['curl','hammer-curl','cable-curl'],Triceps:['db-triceps','pushdown','overhead-triceps'],Forearms:['wrist-curl','reverse-curl','carry'],Shoulders:['shoulder-press','lateral-raise','rear-fly'],Chest:['chest-press','dumbbell-press','pushup'],Back:['row','pulldown','strict-pullup'],Abs:['plank','leg-raise','cable-crunch'],Quads:['squat','leg-press','leg-extension'],Hamstrings:['leg-curl','rdl'],Glutes:['bridge','hip-thrust'],Calves:['calf-raise','seated-calf'],Hips:['hip-abduction','hip-control']};const paths=muscleNames.map(name=>{const matching=all.filter(s=>s.levelDefinitions.some(l=>exercises.find(e=>e.id===l.exerciseId)&&exerciseTargets(exercises.find(e=>e.id===l.exerciseId),name)));const chosen=matching.filter(s=>s.levelDefinitions.some(l=>(primary[name]||[]).includes(l.exerciseId))).map(s=>s.id);const ids=chosen.length?chosen:matching.slice(0,2).map(s=>s.id);return {id:name,name,primarySkillIds:ids,optionalSkillIds:matching.filter(s=>!ids.includes(s.id)).map(s=>s.id),milestones:ids.length<2?[]:[{id:'I',name:name.toUpperCase()+' I',movements:Math.min(2,ids.length),tiersPerMovement:1},{id:'II',name:name.toUpperCase()+' II',movements:Math.min(3,ids.length),tiersPerMovement:2}],revision:1}});return {exercises:muscleExercises,skills,paths}}
