import {stores,DATABASE_VERSION,dayKey,uid} from './store.js';
import {gameSeeds} from './game-data.js';
import {validateBackup} from './backup.js';
export const resetLevels={today:'Reset Today Only',active:'Reset Active Sessions',progression:'Reset Progression Test Data',full:'Full Test Profile Reset'};
const tableSnapshot=async t=>Object.fromEntries(await Promise.all(stores.map(async s=>[s,await t.all(s)])));
const digest=async tables=>{const bytes=new TextEncoder().encode(JSON.stringify(tables));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('')};
export function resetTables(original,{level,date,keepCustom=true,at}){
 if(!resetLevels[level])throw Error('Select a reset level.');const t=structuredClone(original);
 if(level==='full'){const game=gameSeeds();for(const s of stores)t[s]=[];for(const s of ['configurations','exercises','goals','skillDefinitions','equipmentProfiles','musclePaths','gameConfigurations'])t[s]=structuredClone(original[s]);t.gameProfile=[game.profile];t.gameInventory=[game.inventory,game.title];t.templates=structuredClone(original.templates.filter(p=>keepCustom||p.builtIn===true));if(keepCustom)t.personalRecurrences=structuredClone(original.personalRecurrences);return t}
 if(level==='progression'){for(const s of ['attempts','masteryAwards','records','recordEvents','rewards','rewardLedger','gameQuests','gameBadges','bossClears','gameCelebrations','pillarPlans'])t[s]=[];const game=gameSeeds();t.gameProfile=[game.profile];t.gameInventory=[game.inventory,game.title];t.progressionPolicies=[{id:'reset-baseline',at,excludedSessionIds:t.sessions.map(s=>s.id),excludedRecordIds:['routineLogs','checkins','water','events'].flatMap(s=>t[s].map(r=>s+':'+r.id))}];return t}
 const removed=t.sessions.filter(s=>level==='today'?s.date===date:['planned','active','paused'].includes(s.status)).map(s=>s.id);t.sessions=t.sessions.filter(s=>!removed.includes(s.id));
 for(const s of ['records','recordEvents'])t[s]=t[s].filter(r=>!removed.includes(r.sourceSession));t.edits=t.edits.filter(r=>!removed.includes(r.recordId));t.attempts=t.attempts.filter(r=>!removed.includes(r.sessionId));
 t.rewards=t.rewards.filter(r=>!removed.some(id=>r.id==='session:'+id));t.rewardLedger=t.rewardLedger.filter(r=>!removed.some(id=>r.sourceId===id||r.sourceId==='session:'+id));
 if(level==='active')t.events=t.events.filter(e=>!removed.includes(e.sessionId));for(const plan of t.pillarPlans)for(const [id,v] of Object.entries(plan.completed))if(removed.includes(v.sessionId))delete plan.completed[id];
 if(level==='today'){for(const s of ['water','routineLogs','checkins','soreness','dailyStates','attempts','masteryAwards','rewards','rewardLedger','gameBadges','bossClears','gameCelebrations','pillarPlans'])t[s]=t[s].filter(r=>r.date!==date);t.events=t.events.map(e=>e.date===date?{...e,status:'PLANNED',sessionId:removed.includes(e.sessionId)?undefined:e.sessionId}:e);t.gameQuests=t.gameQuests.map(q=>(q.date===date||(q.completedAt&&dayKey(new Date(q.completedAt))===date))?{...q,status:'planned',evidence:[],completedAt:undefined}:q);const game=gameSeeds();t.gameInventory=t.gameInventory.filter(i=>(!i.at||dayKey(new Date(i.at))!==date)||[game.inventory.id,game.title.id].includes(i.id));t.gameProfile=t.gameProfile.map(p=>({...p,title:t.gameInventory.some(i=>i.type==='title'&&i.itemId===p.title)?p.title:game.profile.title,favorites:p.favorites.filter(id=>t.gameBadges.some(b=>b.id===id)),equipped:Object.fromEntries(Object.entries(p.equipped).filter(([slot,id])=>t.gameInventory.some(i=>i.id==='cosmetic:'+id)))}));}
 return t;
}
export function testingActionRegistry(repo,clock){return {
 async previewReset({level,keepCustom=true}){const snapshot=await repo.snapshot();const date=dayKey(clock()),at=clock().toISOString();const result=resetTables(snapshot.tables,{level,keepCustom,date,at});validateBackup({...snapshot,tables:result});return {level,keepCustom,date,profile:repo.name,label:resetLevels[level],fingerprint:await digest(snapshot.tables),reviewedTables:JSON.stringify(snapshot.tables),counts:Object.fromEntries(stores.map(s=>[s,Math.max(0,snapshot.tables[s].length-result[s].length)]).filter(([,n])=>n))}},
 async executeReset({preview,confirmation,acknowledged,backupOffered}){if(confirmation!=='RESET KITTY'||acknowledged!==true||backupOffered!==true||!preview?.fingerprint||preview.profile!==repo.name||preview.date!==dayKey(clock()))throw Error('Review the reset, offer a backup, confirm deletion, and type RESET KITTY.');if(await digest(JSON.parse(preview.reviewedTables))!==preview.fingerprint)throw Error('Reset preview is invalid.');return repo.transact(stores,async t=>{const before=await tableSnapshot(t);/* Check before mutation; hashing outside the live transaction would let another tab race. */const recomputed=resetTables(before,{level:preview.level,keepCustom:preview.keepCustom,date:preview.date,at:clock().toISOString()});const counts=Object.fromEntries(stores.map(s=>[s,Math.max(0,before[s].length-recomputed[s].length)]).filter(([,n])=>n));if(JSON.stringify(counts)!==JSON.stringify(preview.counts)||JSON.stringify(before)!==preview.reviewedTables)throw Error('Data changed after review. Open a fresh reset preview.');validateBackup({format:'kitty-quest-backup',schemaVersion:DATABASE_VERSION,tables:recomputed});for(const s of stores){await t.clear(s);for(const r of recomputed[s])await t.put(s,r)}return {previous:{format:'kitty-quest-backup',profile:repo.name==='kitty-quest-test-profile'?'test':'real',schemaVersion:DATABASE_VERSION,tables:before,exportedAt:clock().toISOString()},level:preview.level}})},
 async testAwardXP({amount=100}){if(repo.name!=='kitty-quest-test-profile')throw Error('Test rewards are available only in the isolated test profile.');if(!Number.isInteger(amount)||amount<1||amount>1000)throw Error('Use 1–1000 test XP.');const date=dayKey(clock()),at=clock().toISOString(),id=uid();return repo.transact(['gameQuests','rewardLedger'],async t=>{await t.put('gameQuests',{id,date,name:'TEST / simulated quest',type:'Personal',minutes:1,priority:1,status:'completed',completedAt:at,evidence:[{test:true}],reward:{xp:amount,coins:0},test:true});await t.put('rewardLedger',{id:'quest:'+id,sourceType:'quest',sourceId:id,amount,coins:0,date,at,reason:'TEST / simulated XP',evidence:[{test:true}]})})}
}}
