import {uid,dayKey,stores} from './store.js';
import {validatePersonalBlock,personalStatuses,validDate,validTime,overlapsProtected} from './schedule.js';
import {evaluateLevel,currentLevel,goalStatuses,recordCandidates,equipmentAllows,substitutions} from './training.js';
export const pipelineStores=['sessions','attempts','skillDefinitions','masteryAwards','goals','records','recordEvents','exercises','progressionPolicies'];
export async function syncTraining(t,at){const data=Object.fromEntries(await Promise.all(pipelineStores.map(async s=>[s,await t.all(s)])));const policy=data.progressionPolicies.find(p=>p.id==='reset-baseline');if(policy)data.sessions=data.sessions.filter(s=>!policy.excludedSessionIds.includes(s.id));const freshRecords=[];const candidates=recordCandidates(data.sessions,data.exercises);await t.clear('records');for(const record of candidates){const old=data.records.find(r=>r.id===record.id),better=!old||(record.lower?record.value<old.value:record.value>old.value);if(better){const id=record.id+':'+record.sourceSet;if(!data.recordEvents.some(e=>e.id===id)){const event={...record,id,recordId:record.id,previous:old?.value??null,at};await t.put('recordEvents',event);freshRecords.push(event)}}await t.put('records',record)}
 for(const skill of data.skillDefinitions){const level=currentLevel(skill,data),state=evaluateLevel(skill,level,data);if(!state.eligible||state.dominated)continue;const goals=goalStatuses(data.goals,data.skillDefinitions,data.masteryAwards);if(level.goalPrerequisites?.some(id=>!goals.find(g=>g.id===id)?.proven))continue;const award={id:skill.id+':'+level.id,skill:skill.id,levelId:level.id,name:skill.name+' · '+level.name,date:dayKey(new Date(at)),at,ruleSnapshot:structuredClone(level)};if(!data.masteryAwards.some(a=>a.id===award.id)){await t.put('masteryAwards',award);data.masteryAwards.push(award)}}return freshRecords}
export async function proofFromSession(t,session,at){if(!session.proof)return;const definitions=await t.all('skillDefinitions'),skill=definitions.find(s=>s.id===session.proof.skill),level=skill?.levelDefinitions.find(l=>l.id===session.proof.levelId);if(!level)return;const rule=level.requirements.find(r=>r.id===session.proof.trialId);const eligible=session.logs.filter(l=>l.exerciseId===(rule?.exerciseId||level.exerciseId));if(!eligible.length)return;const attempt={id:'session:'+session.id+':'+level.id+':'+session.proof.trialId,skill:skill.id,levelId:level.id,level:skill.levelDefinitions.indexOf(level),trial:session.proof.trialId,date:session.date,sessionId:session.id,sets:eligible.length,reps:Math.min(...eligible.map(l=>l.reps||0)),seconds:Math.min(...eligible.map(l=>l.durationSeconds||0)),distance:Math.min(...eligible.map(l=>l.distanceMeters||0)),load:(rule?.loadComparison==='atMost'?Math.max:Math.min)(...eligible.map(l=>l.weight||0)),difficulty:Math.max(...eligible.map(l=>l.difficulty)),form:eligible.every(l=>l.form===true),tempo:eligible.every(l=>l.tempoControlled===true),pain:eligible.some(l=>l.pain),at};await t.put('attempts',attempt)}
export async function materialize(t,date){const recurrences=await t.all('personalRecurrences');for(const r of recurrences){if(r.archived||date<r.date||(r.until&&date>r.until)||!r.weekdays.includes(new Date(date+'T12:00:00').getDay()))continue;const id='personal:'+r.id+':'+date;if(!await t.get('events',id))await t.put('events',{id,date,originalDate:date,recurrenceId:r.id,name:r.name,time:r.time,durationMinutes:r.durationMinutes,category:'Personal Time',protected:true,status:'PLANNED',buffer:0})}}
export function trainingActionRegistry(repo,clock){const at=()=>clock().toISOString();return {
 async syncTraining(){return repo.transact(pipelineStores,t=>syncTraining(t,at()))},
 async logSoreness({muscle,rating}){if(typeof muscle!=='string'||!muscle.trim()||!Number.isInteger(rating)||rating<0||rating>4)throw Error('Select a muscle and soreness from 0–4.');return repo.put('soreness',{id:uid(),date:dayKey(clock()),muscle:muscle.toLowerCase(),rating,at:at()})},
 async saveEquipmentProfile({profile}){if(!profile.id||!profile.name||!Array.isArray(profile.equipment)||profile.equipment.some(e=>typeof e!=='string'))throw Error('Invalid equipment profile.');return repo.put('equipmentProfiles',profile)},
 async setEquipmentContext({profileId}){return repo.transact(['preferences','equipmentProfiles'],async t=>{if(!await t.get('equipmentProfiles',profileId))throw Error('Equipment profile not found.');const pref=await t.get('preferences','user');if(!pref)throw Error('Set up your profile first.');await t.put('preferences',{...pref,equipmentContext:profileId});return profileId})},
 async saveWorkoutTemplate({template}){if(!template.name?.trim()||!Array.isArray(template.exercises)||!template.exercises.length)throw Error('Name your workout and add at least one movement.');for(const e of template.exercises){if(!e.name||!Number.isInteger(e.sets)||e.sets<1||e.sets>100||!Number.isFinite(e.reps)||e.reps<1||e.reps>1000||!Number.isFinite(e.weight)||e.weight<0||e.weight>2000)throw Error('Check each movement’s sets, reps, and load.');for(const k of ['durationSeconds','distanceMeters','restSeconds'])if(e[k]!==undefined&&(!Number.isFinite(e[k])||e[k]<0||e[k]>100000))throw Error('Invalid '+k);if(e.difficultyTarget<1||e.difficultyTarget>10)throw Error('Difficulty target is 1–10.')}return repo.transact(['templates'],async t=>{const prior=template.id?await t.get('templates',template.id):null;const saved={...template,id:template.id||uid(),type:'workout',revision:(prior?.revision||0)+1,updatedAt:at()};await t.put('templates',saved);return saved})},
 async duplicateWorkoutTemplate({templateId}){const templates=await repo.all('templates'),original=templates.find(t=>t.id===templateId&&t.type==='workout');if(!original)throw Error('Template not found.');return this.saveWorkoutTemplate({template:{...structuredClone(original),id:uid(),name:original.name+' / copy',archived:false}})},
 async archiveWorkoutTemplate({templateId}){return repo.transact(['templates'],async t=>{const t0=await t.get('templates',templateId);if(!t0)throw Error('Template not found.');await t.put('templates',{...t0,archived:true,updatedAt:at()})})},
 async recordDominanceAttempt({attempt}){return repo.transact(pipelineStores,async t=>{const skill=(await t.all('skillDefinitions')).find(s=>s.id===attempt.skill),level=skill?.levelDefinitions.find(l=>l.id===attempt.levelId);if(!level||!level.requirements.some(r=>r.id===attempt.trial))throw Error('Select a valid skill level and trial.');const awards=await t.all('masteryAwards');const index=skill.levelDefinitions.indexOf(level);if(skill.levelDefinitions.slice(0,index).some(l=>!awards.some(a=>a.skill===skill.id&&a.levelId===l.id)))throw Error('Prove the previous levels before testing this one.');const a={...attempt,id:attempt.id||uid(),level:index,date:attempt.date||dayKey(clock()),at:at()};for(const k of ['sets','reps','seconds','distance','load'])if(!Number.isFinite(a[k])||a[k]<0)throw Error('Enter valid trial measurements.');if(a.difficulty<1||a.difficulty>10||typeof a.form!=='boolean'||typeof a.pain!=='boolean'||!validDate(a.date))throw Error('Invalid trial feedback.');if(await t.get('attempts',a.id))return await t.get('attempts',a.id);await t.put('attempts',a);await syncTraining(t,at());return a})},
 async saveDominanceRule({skillId,levelId,requirement,protocol='standard',sessions}){return repo.transact(['skillDefinitions','masteryAwards','attempts'],async t=>{const skill=await t.get('skillDefinitions',skillId),level=skill?.levelDefinitions.find(l=>l.id===levelId);if(!level)throw Error('Level not found.');if((await t.all('masteryAwards')).some(a=>a.levelId===levelId)||(await t.all('attempts')).some(a=>a.levelId===levelId||(a.skill===skillId&&a.level===skill.levelDefinitions.indexOf(level))))throw Error('Rules with proof history are protected. Define future levels instead.');if(protocol==='4x100'&&!level.highVolumeEligible)throw Error('High-volume endurance is not enabled for this movement.');if(!requirement?.id||!Number.isInteger(requirement.sets)||requirement.sets<1||requirement.sets>20)throw Error('Invalid trial sets.');for(const k of ['reps','load','seconds','distance'])if(requirement[k]!==undefined&&(!Number.isFinite(requirement[k])||requirement[k]<0||requirement[k]>100000))throw Error('Invalid trial requirement.');const index=level.requirements.findIndex(r=>r.id===requirement.id);if(index<0)throw Error('Trial not found.');const existing=level.requirements[index];if(skill.ladder&&requirement.load!==existing.load)throw Error('Use Configure load ladder to change tier resistance.');if(requirement.exerciseId&&requirement.exerciseId!==existing.exerciseId||requirement.loadComparison&&requirement.loadComparison!==existing.loadComparison)throw Error('Keep the trial movement and resistance direction.');if(sessions!==undefined){if(!Number.isInteger(sessions)||sessions<1||sessions>100)throw Error('Qualifying practice days must be 1–100.');level.sessions=sessions}level.requirements[index]={...existing,...requirement,exerciseId:existing.exerciseId,loadComparison:existing.loadComparison,requiresForm:true,maxDifficulty:9};skill.revision=(skill.revision||0)+1;await t.put('skillDefinitions',skill);return skill})},
 async createPersonalTime({block,recurring=false}){validatePersonalBlock(block,recurring);return repo.transact(['events','personalRecurrences'],async t=>{const saved={...block,id:block.id||uid(),category:'Personal Time',protected:true,status:'PLANNED',buffer:0};if(recurring){const recurrence={...saved,weekdays:[...new Set(block.weekdays)],archived:false};await t.put('personalRecurrences',recurrence);await materialize(t,block.date);return recurrence}await t.put('events',saved);return saved})},
 async updatePersonalTime({eventId,date,time,durationMinutes,status}){return repo.transact(['events'],async t=>{const old=await t.get('events',eventId);if(old?.category!=='Personal Time')throw Error('Personal Time block not found.');const next={...old,date:date||old.date,time:time||old.time,durationMinutes:durationMinutes??old.durationMinutes,status:status||old.status};validatePersonalBlock(next);await t.put('events',next);return next})},
 async archivePersonalRecurrence({recurrenceId}){return repo.transact(['personalRecurrences'],async t=>{const r=await t.get('personalRecurrences',recurrenceId);if(!r)throw Error('Recurrence not found.');await t.put('personalRecurrences',{...r,archived:true})})},
 async materializePersonalTime({date=dayKey(clock())}={}){if(!validDate(date))throw Error('Invalid date.');return repo.transact(['events','personalRecurrences'],t=>materialize(t,date))},
 async scheduleOptionalTraining({sessionId,date,time,durationMinutes}){if(!validDate(date)||!validTime(time)||!Number.isFinite(durationMinutes)||durationMinutes<=0||durationMinutes>1440)throw Error('Invalid schedule duration.');return repo.transact(['events','sessions','personalRecurrences'],async t=>{for(const offset of [-1,0,1]){const neighbor=new Date(date+'T12:00:00');neighbor.setDate(neighbor.getDate()+offset);await materialize(t,dayKey(neighbor))}const s=await t.get('sessions',sessionId);if(s?.kind!=='Extra')throw Error('Select an Extra Training session.');const conflicts=overlapsProtected(await t.all('events'),date,time,durationMinutes);if(conflicts.length)throw Error('Optional training overlaps protected '+conflicts[0].name+'. Choose another time.');const e={id:'extra:'+sessionId,sessionId,date,time,durationMinutes,name:s.name,status:'PLANNED',category:'Training'};await t.put('events',e);return e})}
}}
