import {daysApart,goalStatuses,currentLevel,evaluateLevel,readiness} from './training.js';
import {pillarState} from './game.js';
export const phases=[{name:'FOUNDATION',focus:'Movement patterns, baseline strength, mobility and consistency.'},{name:'BUILD',focus:'Controlled overload, push/pull strength and reduced assistance.'},{name:'DEFINE',focus:'Maintain strength, improve bodyweight control and compare real evidence.'}];
export const skillPaths=[{name:'Push-up',ids:['wall-pushup','high-incline','low-incline','knee-pushup','negative-pushup','pushup','decline-pushup']},{name:'Pull-up',ids:['scapular','supported-hang','hang','assisted-pullup','negative','partial-pullup','strict-pullup']},{name:'Core',ids:['bracing','deadbug','knee-plank','plank','hollow-hold','leg-raise']},{name:'Squat',ids:['supported-squat','squat','split-squat','reverse-lunge','step-up','single-leg-squat']}];
const average=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
export function journey(data,date){const pref=data.preferences.find(p=>p.id==='user')||{},config=data.configurations.find(c=>c.id==='transformation'),start=pref.transformationStart||date,days=Math.max(0,daysApart(date,start)),total=(config?.durationWeeks||12)*7,day=Math.min(days+1,total),week=Math.min(Math.floor(days/7)+1,config?.durationWeeks||12),phase=Math.min(2,Math.floor((week-1)/Math.max(1,(config?.durationWeeks||12)/3)));return {start,days,day,week,total,phase,percent:Math.min(100,Math.round(days/total*100)),final:days>=total-1}}
export function weeklyMeasurements(data,start,date){const values=data.metrics.filter(m=>m.date>=start&&m.date<=date),weeks=[];for(let w=0;w<Math.ceil((daysApart(date,start)+1)/7);w++){const rows=values.filter(m=>daysApart(m.date,start)>=w*7&&daysApart(m.date,start)<(w+1)*7);weeks.push({week:w+1,weight:average(rows.map(m=>m.weight).filter(Number.isFinite)),waist:average(rows.map(m=>m.waist).filter(Number.isFinite))})}return weeks}
export function movementEvidence(data,exerciseId,start,date){const logs=data.sessions.filter(s=>s.date>=start&&s.date<=date&&['completed','partial'].includes(s.status)).flatMap(s=>s.logs.filter(l=>(l.exerciseId||s.exercises[l.exercise]?.exerciseId)===exerciseId&&!l.pain&&l.form).map(l=>({...l,date:s.date}))).sort((a,b)=>a.date.localeCompare(b.date));const definition=data.exercises.find(e=>e.id===exerciseId),assistance=definition?.resistance==='assistance'||exerciseId==='assisted-pullup',measure=l=>assistance?l.weight:definition?.measurement==='duration'?l.durationSeconds||0:l.weight||l.reps;const best=logs.length?logs.reduce((a,b)=>(assistance?measure(b)<measure(a):measure(b)>measure(a))?b:a):null;return {first:logs[0]||null,last:logs.at(-1)||null,best,assistance,unit:assistance?'lb assistance':definition?.measurement==='duration'?'sec':definition?.resistance==='weighted'?'lb':'reps'}}
export function questEvidence(data,date){const j=journey(data,date),measurements=weeklyMeasurements(data,j.start,date),within=s=>s.date>=j.start&&s.date<=date,completed=data.sessions.filter(s=>within(s)&&s.status==='completed'),logs=completed.flatMap(s=>s.logs.map(l=>({session:s,log:l}))),walkMeters=logs.filter(({log})=>['walk','run'].includes(log.exerciseId)).reduce((n,{log})=>n+(log.distanceMeters||0),0),mobility=completed.filter(s=>s.pillarId==='mobility'||s.logs.some(l=>l.exerciseId==='mobility')).length,prs=data.recordEvents.filter(within),recovery=data.checkins.filter(c=>within(c)&&c.type==='recovery');return {journey:j,measurements,completed,walkMeters,mobility,prs,recovery,pullup:goalStatuses(data.goals,data.skillDefinitions,data.masteryAwards).find(g=>g.id==='first-pullup'),pillars:pillarState(data,date)}}
export function safetyAdvice(check){if(['joint','sharp','instability'].includes(check.pain))return {level:'JOINT WARNING',message:'Stop the painful movement. Choose a pain-free alternative or skip it. Persistent instability or significant pain should be evaluated by a qualified healthcare professional.',progress:false};if(check.pain==='soreness'||check.sleep<=2||check.energy<=2)return {level:'LIGHT / RECOVERY',message:'Reduce intensity, choose mobility or rest. Recovery counts; do not increase resistance today.',progress:false};return {level:'NORMAL / CONTROLLED',message:'Keep most working sets around 1–3 good reps in reserve. Progress only with controlled, pain-free performance.',progress:true}}
