import {describe,test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {Repository,DATABASE_VERSION,stores} from '../dist/store.js';
import {createActions} from '../dist/actions.js';
import {validateBackup,restoreBackup} from '../dist/backup.js';
import {balances,playerLevel,streak,activityDates,trend,bossProgress,transformationSummary,dailyClear,nextCelebration} from '../dist/game.js';
import {gameConfiguration,gameStores,pillars} from '../dist/game-data.js';

describe('Phase 3 evidence and game economy',()=>{
 let repo,actions,now,factory;
 beforeEach(async()=>{factory=new IDBFactory();now=new Date(2026,8,18,12);repo=await new Repository(factory,'game').open();actions=createActions(repo,()=>now);await actions.ensureDay();await actions.dispatch('syncGame')});
 afterEach(()=>repo.close());
 const data=async()=>(await repo.snapshot()).tables;
 const sync=()=>actions.dispatch('syncGame');
 const start=(more={})=>actions.dispatch('startSession',{kind:'Extra',name:'Controlled exposure',exercises:[{exerciseId:'curl',name:'Biceps curl',sets:1,reps:8,weight:5}],...more});
 const log=(s,more={})=>actions.dispatch('logSet',{sessionId:s.id,exercise:0,reps:8,weight:5,difficulty:6,form:true,pain:false,notes:'',...more});
 const finish=s=>actions.dispatch('completeSession',{sessionId:s.id,difficulty:6});
 async function exposure(pillarId,more={}){const id={body:'wall-pushup',mobility:'supported-squat',strength:'curl',movement:'walk'}[pillarId];const definition=(await repo.all('exercises')).find(e=>e.id===id);const s=await start({pillarId,exercises:[{exerciseId:id,name:definition.name,sets:1,reps:8,weight:id==='curl'?5:0,...(id==='walk'?{distanceMeters:500}: {})}],...more});await log(s,{weight:id==='curl'?5:0,...(id==='walk'?{distanceMeters:500}: {})});await finish(s);return s}
 async function routines(){const state=(await repo.all('dailyStates')).find(s=>s.date===now.toISOString().slice(0,10));for(let task=0;task<state.routineTasks.length;task++)await actions.dispatch('setRoutineTask',{task,done:true})}
 async function provePush(){let day=18;for(let index=0;index<=4;index++){const skill=(await repo.all('skillDefinitions')).find(s=>s.id==='push'),level=skill.levelDefinitions[index];for(let i=0;i<3;i++){now=new Date(2026,8,day++,12);for(const r of level.requirements)await actions.dispatch('recordDominanceAttempt',{attempt:{skill:'push',levelId:level.id,trial:r.id,sets:r.sets,reps:r.reps||0,seconds:0,distance:0,load:0,difficulty:6,form:true,pain:false}})}}}
 test('Concurrent completion awards XP and coins exactly once per source',async()=>{const s=await start();await log(s);await Promise.all([finish(s),finish(s),finish(s)]);await sync();const ledger=await repo.all('rewardLedger');assert.equal(ledger.filter(r=>r.id==='session:'+s.id).length,1);assert.equal(ledger.find(r=>r.id==='session:'+s.id).amount,50);assert.equal(ledger.find(r=>r.id==='session:'+s.id).coins,10)});
 test('Daily session cap prevents farming unlimited completions',async()=>{for(let i=0;i<6;i++){const s=await start();await log(s);await finish(s)}const ledger=await repo.all('rewardLedger');assert.equal(ledger.filter(r=>r.sourceType==='session').length,gameConfiguration.sessionDailyLimit)});
 test('Tiny water and repeated routine toggles cannot farm XP',async()=>{for(let i=0;i<10;i++)await actions.addWater({amount:1});await routines();const first=balances(await data());await actions.dispatch('setRoutineTask',{task:0,done:false});await actions.dispatch('setRoutineTask',{task:0,done:true});await sync();assert.deepEqual(balances(await data()),first);assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='routine').length,1);assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='water').length,0)});
 test('Player level curve is deterministic and independent from mastery',async()=>{assert.equal(playerLevel(499,gameConfiguration).level,1);assert.equal(playerLevel(500,gameConfiguration).level,2);assert.equal(playerLevel(1100,gameConfiguration).level,3);assert.deepEqual(playerLevel(20000,gameConfiguration),playerLevel(20000,structuredClone(gameConfiguration)));assert.equal((await repo.all('masteryAwards')).length,0)});
 test('Quad Clear and secret Four for Four award once per day',async()=>{for(const p of pillars)await exposure(p.id);await sync();await sync();assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='quad').length,1);assert.equal((await repo.all('gameBadges')).filter(b=>b.id==='four-for-four').length,1);assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='pillar').length,4)});
 test('Light and recovery exposures count without maximal effort',async()=>{await actions.dispatch('savePillarPlan',{items:pillars.map(p=>({id:p.id,planned:true,mode:'Recovery'}))});for(const p of pillars)await exposure(p.id,{mode:'Recovery'});assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='quad').length,1);assert.ok((await repo.all('gameBadges')).some(b=>b.id==='smart-recovery'))});
 test('Started daily pillar plan cannot be rewritten to trigger a second clear',async()=>{await exposure('body');await assert.rejects(()=>actions.dispatch('savePillarPlan',{items:pillars.map(p=>({id:p.id,planned:false,mode:'Recovery'}))}),/preserved/)});
 test('Incomplete planned sets do not complete an exposure',async()=>{const s=await start({pillarId:'body',exercises:[{exerciseId:'wall-pushup',name:'Wall push-up',sets:3,reps:8,weight:0}]});await log(s,{weight:0});await finish(s);assert.equal((await repo.all('pillarPlans'))[0].completed.body,undefined)});
 test('Boss clear, badge and boss reward cannot duplicate',async()=>{await provePush();await sync();await sync();assert.equal((await repo.all('bossClears')).filter(b=>b.id==='ground').length,1);assert.equal((await repo.all('gameBadges')).filter(b=>b.id==='boss:ground').length,1);assert.equal((await repo.all('rewardLedger')).filter(r=>r.id==='boss:ground').length,1);assert.equal(bossProgress(await data(),now.toISOString().slice(0,10)).find(b=>b.id==='gravity').complete,false)});
 test('XP and cosmetic purchases cannot create physical proof',async()=>{await exposure('strength');await exposure('body');const awards=await repo.all('masteryAwards');await actions.dispatch('purchaseCosmetic',{itemId:'quiet-stars'});await actions.dispatch('equipGameItem',{type:'cosmetic',itemId:'quiet-stars'});assert.deepEqual(await repo.all('masteryAwards'),awards);assert.equal((await repo.all('bossClears')).length,0)});
 test('Concurrent cosmetic purchases debit once and preserve nonnegative balance',async()=>{await exposure('strength');await exposure('body');const before=balances(await data()).coins;await Promise.all([actions.dispatch('purchaseCosmetic',{itemId:'quiet-stars'}),actions.dispatch('purchaseCosmetic',{itemId:'quiet-stars'})]);assert.equal(balances(await data()).coins,before-25);assert.equal((await repo.all('rewardLedger')).filter(r=>r.id==='purchase:quiet-stars').length,1);await assert.rejects(()=>actions.dispatch('purchaseCosmetic',{itemId:'white-star'}),/Not enough/)});
 test('All game tables restore and replay without duplicate rewards or bosses',async()=>{for(const p of pillars)await exposure(p.id);const backup=await repo.snapshot();validateBackup(backup);await restoreBackup(backup,repo);await sync();assert.deepEqual(await repo.all('rewardLedger'),backup.tables.rewardLedger);assert.deepEqual(await repo.all('gameBadges'),backup.tables.gameBadges);for(const name of gameStores)assert.ok(Array.isArray(backup.tables[name]))});
 test('Version 5 backup preserves old rewards once in the new ledger',async()=>{const s=await start();await log(s);await finish(s);const backup=await repo.snapshot();backup.schemaVersion=5;for(const name of gameStores)delete backup.tables[name];const upgraded=validateBackup(backup);assert.equal(upgraded.schemaVersion,DATABASE_VERSION);await restoreBackup(upgraded,repo);await sync();const ledger=await repo.all('rewardLedger');assert.equal(ledger.filter(r=>r.sourceType==='legacy').length,1);assert.equal(ledger.filter(r=>r.id==='session:'+s.id).length,0)});
 test('Broken streak changes count only, leaving earned progress untouched',async()=>{await exposure('strength');const before=await repo.snapshot();now=new Date(2026,8,23,12);await actions.ensureDay();assert.equal(streak(activityDates(await data()),'2026-09-23').current,0);for(const name of ['rewardLedger','gameBadges','masteryAwards','records','sessions'])assert.deepEqual(await repo.all(name),before.tables[name]);assert.equal(streak(['2026-09-18','2026-09-19','2026-09-23'],'2026-09-23').best,2)});
 test('Quest completions and chain proof survive replay and reopen',async()=>{await provePush();const completed=await repo.all('gameQuests'),awards=await repo.all('masteryAwards');repo.close();repo=await new Repository(factory,'game').open();actions=createActions(repo,()=>now);await sync();for(const q of completed.filter(q=>q.status==='completed'))assert.equal((await repo.all('gameQuests')).find(x=>x.id===q.id).status,'completed');assert.deepEqual(await repo.all('masteryAwards'),awards);assert.ok(awards.some(a=>a.levelId==='push-4'))});
 test('Secret Still Hungry requires an Extra after the planned day is honored',async()=>{for(const p of pillars)await exposure(p.id);await routines();assert.equal(dailyClear(await data(),'2026-09-18'),true);now=new Date(2026,8,18,13);const extra=await start();await log(extra);await finish(extra);assert.ok((await repo.all('gameBadges')).some(b=>b.id==='still-hungry'))});
 test('Balance achievement records schedule preservation, never relationship duration',async()=>{await actions.dispatch('createPersonalTime',{block:{name:'Bae Time 🤍',date:'2026-09-18',time:'20:00',durationMinutes:120}});for(const p of pillars)await exposure(p.id);await routines();await sync();const badge=(await repo.all('gameBadges')).find(b=>b.id==='balance');assert.ok(badge);assert.equal(badge.reward.xp,0);assert.equal(badge.reward.coins,0);assert.equal(JSON.stringify(badge).includes('durationMinutes'),false)});
 test('Painful workouts earn no session reward; stopping safely preserves data',async()=>{const s=await start();await log(s,{pain:true});await actions.dispatch('stopSafely',{sessionId:s.id});const first=balances(await data());await sync();assert.deepEqual(balances(await data()),first);assert.equal((await repo.all('sessions'))[0].status,'partial');assert.equal((await repo.all('sessions'))[0].logs.length,1);assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='session').length,0);assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='safetyStop').length,1)});
 test('Transformation trend requires separate multi-day windows, not one scale reading',()=>{const c=gameConfiguration.transformation;assert.equal(trend([{id:'one',date:'2026-09-18',weight:200}],'weight','2026-09-18',c).change,null);const rows=[...Array.from({length:3},(_,i)=>({id:'a'+i,date:'2026-09-'+(18+i),weight:216})),...Array.from({length:3},(_,i)=>({id:'b'+i,date:'2026-10-0'+(1+i),weight:210}))];const result=trend(rows,'weight','2026-10-03',c);assert.equal(result.change,6);assert.equal(result.enough,true)});
 test('History corrections cannot trigger new game rewards',async()=>{const s=await start(),set=await log(s);await finish(s);const ledger=await repo.all('rewardLedger');await actions.correctSet({sessionId:s.id,setId:set.id,changes:{reps:100,weight:100},reason:'Corrected a mistaken entry'});await sync();assert.deepEqual(await repo.all('rewardLedger'),ledger)});
 test('Personal quest can only be completed and rewarded once',async()=>{const q=await actions.dispatch('createPersonalQuest',{name:'Prepare tomorrow',minutes:10,description:'Pack the bag for tomorrow.'});await actions.dispatch('completePersonalQuest',{questId:q.id});await actions.dispatch('completePersonalQuest',{questId:q.id});assert.equal((await repo.all('rewardLedger')).filter(r=>r.id==='quest:'+q.id).length,1);await assert.rejects(()=>actions.dispatch('createPersonalQuest',{name:'Another',minutes:5,description:'Task'}),/already planned/)});
 test('Malformed game ledger restore is rejected without modifying the database',async()=>{await exposure('strength');const original=await repo.snapshot(),bad=structuredClone(original);bad.tables.rewardLedger[0].amount=-50;await assert.rejects(()=>restoreBackup(bad,repo),/game backup/);assert.deepEqual((await repo.snapshot()).tables,original.tables)});
 test('Real IndexedDB version 5 upgrade retains legacy XP and coins once',async()=>{await exposure('strength');const backup=await repo.snapshot();repo.close();await new Promise((resolve,reject)=>{const r=factory.open('version-five',5);r.onupgradeneeded=()=>{for(const name of stores.filter(s=>!gameStores.includes(s)&&!['musclePaths','progressionPolicies'].includes(s))){const s=r.result.createObjectStore(name,{keyPath:'id'});for(const row of backup.tables[name])s.put(row)}};r.onsuccess=()=>{r.result.close();resolve()};r.onerror=()=>reject(r.error)});repo=await new Repository(factory,'version-five').open();actions=createActions(repo,()=>now);assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='legacy').length,1);await sync();assert.equal((await repo.all('rewardLedger')).filter(r=>r.sourceType==='session').length,0)});
 test('Transformation awards use multi-day trends and configurable journey duration',async()=>{await repo.put('preferences',{id:'user',name:'Test',mode:'Quiet',waterTarget:80,transformationStart:'2026-09-18',memory:{training:true,metrics:true,schedule:true,goals:true}});const configuration=(await repo.all('configurations'))[0];await actions.saveConfiguration({configuration:{...configuration,durationWeeks:2}});for(const [date,weight] of [['2026-09-18',216],['2026-09-19',216],['2026-09-20',216],['2026-10-01',210],['2026-10-02',210],['2026-10-03',210]])await repo.put('metrics',{id:date,date,weight,waist:null,notes:''});for(const date of ['2026-09-18','2026-09-25','2026-10-02'])await repo.put('checkins',{id:date,date,type:'weekly',sleep:7,energy:7,hunger:5,soreness:0,weight:null,waist:null,performance:''});now=new Date(2026,9,3,12);await sync();assert.ok((await repo.all('gameBadges')).some(b=>b.id==='trend5'));assert.equal((await repo.all('bossClears')).find(b=>b.id==='transformation').stats.durationWeeks,2);const before=await repo.all('rewardLedger');await sync();assert.deepEqual(await repo.all('rewardLedger'),before)});
 test('Repeated same-week check-ins cannot manufacture transformation completion',async()=>{await repo.put('preferences',{id:'user',name:'Test',mode:'Quiet',waterTarget:80,transformationStart:'2026-06-01',memory:{}});for(let i=0;i<3;i++)await repo.put('checkins',{id:'check-'+i,date:'2026-09-18',type:'weekly',sleep:7,energy:7,hunger:5,soreness:0,weight:null,waist:null,performance:''});const summary=transformationSummary(await data(),'2026-09-18');assert.equal(summary.checkins.length,1);assert.equal(summary.complete,false)});
 test('Full celebrations queue during workouts and Off leaves records accessible',()=>{const queued={sessions:[{id:'active',status:'active'}],gameCelebrations:[{id:'boss:gravity',type:'boss',name:'Gravity I',seen:false}]};assert.equal(nextCelebration(queued,{celebrationIntensity:'Full'}),null);queued.sessions[0].status='completed';assert.equal(nextCelebration(queued,{celebrationIntensity:'Full'}).id,'boss:gravity');assert.equal(nextCelebration(queued,{celebrationIntensity:'Off'}),null);assert.equal(queued.gameCelebrations[0].seen,false)});
 test('A completed Extra spanning midnight cannot falsely preserve Bae Time',async()=>{await repo.put('sessions',{id:'overnight',kind:'Extra',date:'2026-09-17',name:'Overnight extra',status:'completed',startedAt:'2026-09-17T23:30:00-04:00',completedAt:'2026-09-18T01:30:00-04:00',exercises:[{exerciseId:'curl',name:'Biceps curl',sets:1,reps:8,weight:5}],logs:[{id:'overnight-set',exercise:0,exerciseId:'curl',name:'Biceps curl',reps:8,weight:5,difficulty:6,form:true,pain:false}]});await actions.dispatch('createPersonalTime',{block:{name:'Bae Time 🤍',date:'2026-09-18',time:'00:30',durationMinutes:60}});for(const p of pillars)await exposure(p.id);await routines();await sync();assert.equal((await repo.all('gameBadges')).some(b=>b.id==='balance'),false)});
 test('Recovery recommendation reward requires actual low-readiness provenance',async()=>{const normal=await start({mode:'Light / Rebuild',recommendation:{source:'still-hungry',lowReadiness:true}});assert.equal(normal.recommendation.lowReadiness,false);await log(normal);await finish(normal);assert.equal((await repo.all('gameBadges')).some(b=>b.id==='respect-recovery'),false);await actions.dispatch('logSoreness',{muscle:'Biceps',rating:4});const recovery=await start({mode:'Light / Rebuild',recommendation:{source:'still-hungry',lowReadiness:true}});assert.equal(recovery.recommendation.lowReadiness,true);await log(recovery);await finish(recovery);assert.ok((await repo.all('gameBadges')).some(b=>b.id==='respect-recovery'))});
 test('Weekly challenges account for days remaining when joining late in the week',async()=>{const quests=await repo.all('gameQuests');assert.equal(quests.find(q=>q.kind==='quad').target,3);assert.ok(quests.find(q=>q.kind==='walking').target<=500)});
 test('A tracked typo correction does not erase an activity streak',async()=>{const s=await start(),set=await log(s);await finish(s);const before=streak(activityDates(await data()),'2026-09-18');await actions.correctSet({sessionId:s.id,setId:set.id,changes:{reps:9},reason:'Fixed a typo'});assert.deepEqual(streak(activityDates(await data()),'2026-09-18'),before)});
 test('Game reward write failure rolls back awards and safely retries a saved completion',async()=>{const s=await start();await log(s);const original=repo.transact.bind(repo);repo.transact=(names,work,mode)=>original(names,t=>work({...t,put:async(store,row)=>{if(store==='rewardLedger')throw Error('Simulated game storage failure');return t.put(store,row)}}),mode);await assert.rejects(()=>finish(s),/game storage failure/);repo.transact=original;assert.equal((await repo.all('sessions'))[0].status,'completed');assert.equal((await repo.all('rewardLedger')).length,0);await finish(s);assert.equal((await repo.all('rewardLedger')).filter(r=>r.id==='session:'+s.id).length,1);assert.equal((await repo.all('gameBadges')).filter(b=>b.id==='first-workout').length,1)});
});
